[project]
name = "ansible-role-testing"
version = "0.1.0"
description = "Testing dependencies for 1995parham ansible role"
requires-python = ">=3.12"
dependencies = [
  "molecule>=6.0.0",
  "molecule-plugins[docker]>=23.5.0",
  "docker>=6.0.0",
  "ansible-core>=2.15.0",
]
