---
- name: install packages [arch]
  become: true
  community.general.pacman:
    state: present
    update_cache: true
    name:
      - git
      - curl
      - atop
      - zsh
      - tmux
      - bat
      - vim
      - neovim
      - jq
      - htop
      - python-pynvim
      - yamllint
      - mtr
      - inetutils
      - dog
      - man-pages
      - base-devel

- name: color in pacman
  become: true
  replace:
    replace: Color
    regexp: '^#Color$'
    path: /etc/pacman.conf

- name: fix locale.gen file
  become: true
  replace:
    replace: 'en_US.UTF-8 UTF-8'
    regexp: '^LANG='
    path: /etc/locale.gen

- name: clone yay from aur
  become: false
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "$HOME/yay"
