---
- name: install packages [arch]
  become: true
  community.general.pacman:
    state: present
    name:
      - git
      - curl
      - atop
      - zsh
      - tmux
      - bat
      - vim
      - jq
      - htop
      - yamllint
      - mtr
      - inetutils
      - dog
      - man-pages
      - base-devel

- name: color in pacman
  become: true
  ansible.builtin.replace:
    replace: Color
    regexp: '^#Color$'
    path: /etc/pacman.conf

- name: pacman loves candy
  become: true
  ansible.builtin.lineinfile:
    insertafter: 'Color'
    path: /etc/pacman.conf
    search_string: 'ILoveCandy'
    line: ILoveCandy

- name: fix locale.gen file
  become: true
  ansible.builtin.replace:
    replace: 'en_US.UTF-8 UTF-8'
    regexp: '^LANG='
    path: /etc/locale.gen
