---
- name: Install common packages [arch]
  become: true
  community.general.pacman:
    state: present
    name: "{{ common_packages }}"

- name: Install Arch-specific packages
  become: true
  community.general.pacman:
    state: present
    name: "{{ arch_packages }}"

- name: Color in pacman
  become: true
  ansible.builtin.replace:
    replace: Color
    regexp: '^#Color$'
    path: /etc/pacman.conf

- name: Pacman loves candy
  become: true
  ansible.builtin.lineinfile:
    insertafter: 'Color'
    path: /etc/pacman.conf
    search_string: 'ILoveCandy'
    line: ILoveCandy

- name: Uncomment en_US.UTF-8 in locale.gen file
  become: true
  ansible.builtin.replace:
    replace: 'en_US.UTF-8 UTF-8'
    regexp: '^#en_US.UTF-8 UTF-8'
    path: /etc/locale.gen
