---
- name: install packages [arch]
  become: true
  pacman:
    state: present
    update_cache: true
    name: git, curl, atop, zsh, tmux, bat, vim, neovim, jq, htop, python-pynvim, yamllint, mtr

- name: color in pacman
  become: true
  replace:
    replace: Color
    regexp: '^#Color$'
    path: /etc/pacman.conf

- name: fix locale.gen file
  become: true
  replace:
    replace: 'en_US.UTF-8 UTF-8'
    regexp: '^LANG='
    path: /etc/locale.gen
