---
- name: update cache if the last update is more than 3600 seconds ago [debian]
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600
- name: install packages [debian]
  become: true
  apt:
    pkg:
      - htop
      - atop
      - aria2
      - curl
      - tmux
      - bat
      - neovim
      - python3-pynvim
      - jq
      - yamllint
      - bmon
      - zsh
    state: present
