---
- name: Install common packages [debian]
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg: "{{ common_packages }}"
    state: present

- name: Install Debian-specific packages
  become: true
  ansible.builtin.apt:
    pkg: "{{ debian_packages }}"
    state: present
