---
- name: Install packages [debian]
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - htop
      - atop
      - aria2
      - curl
      - tmux
      - bat
      - jq
      - yamllint
      - bmon
      - btop
      - zsh
    state: present
