---
- name: Clone dotfiles
  become: false
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_home }}"
    update: true
  register: dotfiles_git_update

- name: Install dotfiles
  become: false
  ansible.builtin.shell:
    cmd: yes Y | {{ dotfiles_home }}/install.sh -y
  when: dotfiles_git_update.after != dotfiles_git_update.before

- name: Change user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
