---
- name: Clone dotfiles
  become: false
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_home }}"
    accept_hostkey: true
    update: true
  register: dotfiles_git_update

- name: Install zsh
  become: false
  ansible.builtin.shell: "{{ dotfiles_home }}/start.sh -y zsh"
  when: dotfiles_git_update.after != dotfiles_git_update.before
  changed_when: dotfiles_git_update.after != dotfiles_git_update.before

- name: Install bash
  become: false
  ansible.builtin.shell: "{{ dotfiles_home }}/start.sh -y bash"
  when: dotfiles_git_update.after != dotfiles_git_update.before
  changed_when: dotfiles_git_update.after != dotfiles_git_update.before

- name: Install env
  become: false
  ansible.builtin.shell: "{{ dotfiles_home }}/start.sh -y env"
  when: dotfiles_git_update.after != dotfiles_git_update.before
  changed_when: dotfiles_git_update.after != dotfiles_git_update.before

- name: Install dotfiles
  become: false
  ansible.builtin.shell: "{{ dotfiles_home }}/install.sh"
  when: dotfiles_git_update.after != dotfiles_git_update.before
  changed_when: dotfiles_git_update.after != dotfiles_git_update.before

- name: Install starship
  become: false
  ansible.builtin.shell: "{{ dotfiles_home }}/start.sh -y starship"
  when: dotfiles_git_update.after != dotfiles_git_update.before
  changed_when: dotfiles_git_update.after != dotfiles_git_update.before
