---
- name: Setup git name
  become: false
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_name }}"

- name: Setup git email
  become: false
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"
