---
- name: Ensure localisation files are available for {{ config_system_locale }}
  become: true
  community.general.locale_gen:
    name: "{{ config_system_locale }}"
    state: present

- name: >
    Ensure localisation files are available for {{ config_system_language }}
  become: true
  community.general.locale_gen:
    name: "{{ config_system_language }}"
    state: present

- name: Get current locale and language configuration
  ansible.builtin.command: localectl status
  register: locale_status
  changed_when: false

- name: Parse 'LANG' from current locale and language configuration
  ansible.builtin.set_fact:
    locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

- name: Parse 'LANGUAGE' from current locale and language configuration
  ansible.builtin.set_fact:
    locale_language: "{{ locale_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale_lang], true) | first }}"

- name: >
    Configure locale and language to {{ config_system_locale }}{{ config_system_language }}
  become: true
  ansible.builtin.command: localectl set-locale LANG={{ config_system_locale }} LANGUAGE={{ config_system_language }}
  changed_when: locale_lang != config_system_locale or locale_language != config_system_language
