---
- name: debian
  when: ansible_os_family == 'Debian'
  ansible.builtin.import_tasks: debian.yml

- name: arch
  when: ansible_os_family == 'Archlinux'
  ansible.builtin.import_tasks: arch.yml

- name: locale
  when: config_system_enabled == 'true'
  ansible.builtin.import_tasks: locale.yml

- name: dotfiles
  ansible.builtin.import_tasks: dotfiles.yml

- name: git
  ansible.builtin.import_tasks: git.yml

- name: keys
  ansible.builtin.import_tasks: keys.yml
