---
- name: install packages [debian]
  when: ansible_os_family == 'Debian'
  become: true
  apt:
    update_cache: true
    pkg:
      - htop
      - atop
      - aria2
      - curl
      - tmux
      - bat
      - neovim
      - python3-pynvim
      - jq
      - yamllint
      - bmon
      - zsh
    state: present

- name: install packages [arch]
  when: ansible_os_family == 'Archlinux'
  become: true
  pacman:
    state: present
    update_cache: true
    name: git, curl, atop, zsh, tmux, bat, vim, neovim, jq, htop, python-pynvim, yamllint

- name: color in pacman
  when: ansible_os_family == 'Archlinux'
  become: true
  replace:
    replace: Color
    regexp: '^#Color$'
    path: /etc/pacman.conf

- name: clone dotfiles
  become: false
  git:
    repo: https://github.com/1995parham/dotfiles
    dest: "{{ dotfiles_home }}"

- name: install dotfiles
  become: false
  ansible.builtin.shell:
    cmd: yes Y | {{ dotfiles_home }}/install.sh -y

- name: setup git local configuration file
  file:
    path: $HOME/.gitconfig
    state: touch

- name: setup git name and email
  ansible.builtin.shell:
    cmd: git config --global user.name "{{ git_name }}" && git config --global user.email "{{ git_email }}"

- name: change user shell to zsh
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
