---
- name: install packages
  when: ansible_os_family == 'Ubuntu'
  become: true
  apt:
    update_cache: true
    pkg:
      - htop
      - atop
      - aria2
      - curl
      - tmux
      - bat
      - neovim
      - python3-pynvim
      - jq
      - yamllint
      - bmon
      - zsh
    state: present

- name: install packages
  when: ansible_os_family == 'Arch'
  become: true
  apt:
    update_cache: true
    pkg:
      - htop
      - atop
      - aria2
      - curl
      - tmux
      - bat
      - neovim
      - python-pynvim
      - jq
      - yamllint
      - bmon
      - zsh
    state: present

- name: clone dotfiles
  become: false
  git:
    repo: https://github.com/1995parham/dotfiles
    dest: $HOME/Documents/dotfiles

- name: install dotfiles
  become: false
  ansible.builtin.shell:
    cmd: yes Y | $HOME/Documents/dotfiles/install.sh -y

- name: change user shell to zsh
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
