---
# Purpose: assert that the instance really ended up in the expected state.
# Molecule calls this playbook with `molecule verify`.
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Check if dotfiles directory exists
      ansible.builtin.stat:
        path: /home/testuser/.dotfiles
      register: dotfiles_dir

    - name: Verify dotfiles directory was created
      ansible.builtin.assert:
        that:
          - dotfiles_dir.stat.exists
          - dotfiles_dir.stat.isdir
        fail_msg: "Dotfiles directory was not created"
