---
setup_github_keys_username: "1995parham"

setup_dotfiles_home: "~/dotfiles"
setup_dotfiles_repo: "https://github.com/1995parham/dotfiles"
setup_dotfiles_version: "main"

setup_git_name: "Parham Alvani"
setup_git_email: "parham.alvani@gmail.com"

setup_config_system_enabled: false
setup_config_system_locale: 'en_US.UTF-8'
setup_config_system_language: 'en_US.UTF-8'
