---
- name: Ensure localisation files are available for {{ setup_config_system_locale }}
  become: true
  community.general.locale_gen:
    name: "{{ setup_config_system_locale }}"
    state: present

- name: >
    Ensure localisation files are available for {{ setup_config_system_language }}
  become: true
  community.general.locale_gen:
    name: "{{ setup_config_system_language }}"
    state: present

- name: Get current locale and language configuration
  ansible.builtin.command: localectl status
  register: setup_locale_status
  changed_when: false

- name: Parse 'LANG' from current locale and language configuration
  ansible.builtin.set_fact:
    setup_locale_lang: "{{ setup_locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

- name: Parse 'LANGUAGE' from current locale and language configuration
  ansible.builtin.set_fact:
    setup_locale_language: "{{ setup_locale_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([setup_locale_lang], true) | first }}"

- name: >
    Configure locale and language
  become: true
  ansible.builtin.command: localectl set-locale LANG={{ setup_config_system_locale }} LANGUAGE={{ setup_config_system_language }}
  changed_when: setup_locale_lang != setup_config_system_locale or setup_locale_language != setup_config_system_language
