---
name: ci
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: install ansible
        run: |
          python -m pip install --upgrade ansible ansible-lint
      - name: create ansible.cfg with correct roles_path
        run: printf '[defaults]\nroles_path=../' > ansible.cfg

      - name: ansible lint
        run: ansible-lint

      - name: basic ansible role syntax check
        run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check
      - name: run test playbook which installs 1995parham dotfiles
        run: ansible-playbook tests/test.yml -i tests/inventory --become

      - name: test symbolic links
        run: test "$(readlink -f ~/.zshrc.shared)" = "$HOME/dotfiles/zsh/zshrc.shared"
      - name: check command existance in both shells
        run: bash -c hash nvim batcat bmon
      - run: zsh -c hash nvim batcat bmon
        name: check command existance in both shells
