---
name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get version from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build and publish to Galaxy
        uses: artis3n/ansible_galaxy_collection@v3
        with:
          api_key: "${{ secrets.GALAXY_API_KEY }}"
          galaxy_version: "${{ env.RELEASE_VERSION }}"
